export const sampleProducts = [
  {
    ProductName: "WP-001001",
    ProductID: "WP-001001",
    SupplierID: 1,
    CategoryID: 1,
    QuantityPerUnit: "10 boxes x 20 bags",
    UnitPrice: 18,
    UnitsInStock: 39,
    UnitsOnOrder: 0,
    ReorderLevel: 10,
    Status: "Approved",
    Category: {
      CategoryID: 1,
      CategoryName: "Beverages",
      Description: "Soft drinks, coffees, teas, beers, and ales",
    },
    FirstOrderedOn: new Date(2022, 2, 20),
    LastOrderedOn: new Date(2022, 4, 22),
  },
  {
    ProductID: "WP-001001",
    ProductName: "WP-001001",
    SupplierID: 1,
    CategoryID: 1,
    QuantityPerUnit: "24 - 12 oz bottles",
    UnitPrice: 19,
    UnitsInStock: 17,
    UnitsOnOrder: 40,
    ReorderLevel: 25,
    Status: "Draft",
    Category: {
      CategoryID: 1,
      CategoryName: "Beverages",
      Description: "Soft drinks, coffees, teas, beers, and ales",
    },
    FirstOrderedOn: new Date(2022, 2, 20),
    LastOrderedOn: new Date(2022, 4, 22),
  },
  {
    ProductID: "WP-0010012",
    ProductName: "WP-0010012",
    SupplierID: 1,
    CategoryID: 2,
    QuantityPerUnit: "12 - 550 ml bottles",
    UnitPrice: 10,
    UnitsInStock: 13,
    UnitsOnOrder: 70,
    ReorderLevel: 25,
    Status: "Validated",
    Category: {
      CategoryID: 2,
      CategoryName: "Condiments",
      Description: "Sweet and savory sauces, relishes, spreads, and seasonings",
    },
    FirstOrderedOn: new Date(2022, 3, 20),
    LastOrderedOn: new Date(2022, 5, 22),
  },
  {
    ProductID: "WP-0010015",
    ProductName: "WP-0010015",
    SupplierID: 2,
    CategoryID: 2,
    QuantityPerUnit: "48 - 6 oz jars",
    UnitPrice: 22,
    UnitsInStock: 53,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Status: "Validated",
    Category: {
      CategoryID: 2,
      CategoryName: "Condiments",
      Description: "Sweet and savory sauces, relishes, spreads, and seasonings",
    },
    FirstOrderedOn: new Date(2022, 4, 20),
    LastOrderedOn: new Date(2022, 6, 22),
  },
  {
    ProductID: "WP-0010018",
    ProductName: "WP-0010018",
    SupplierID: 2,
    CategoryID: 2,
    QuantityPerUnit: "36 boxes",
    UnitPrice: 21.35,
    UnitsInStock: 0,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Status: "Completed",
    Category: {
      CategoryID: 2,
      CategoryName: "Condiments",
      Description: "Sweet and savory sauces, relishes, spreads, and seasonings",
    },
    FirstOrderedOn: new Date(2022, 5, 20),
    LastOrderedOn: new Date(2022, 7, 22),
  },
  {
    ProductID: "WP-0010019",
    ProductName: "WP-0010019",
    SupplierID: 3,
    CategoryID: 2,
    QuantityPerUnit: "12 - 8 oz jars",
    UnitPrice: 25,
    UnitsInStock: 120,
    UnitsOnOrder: 0,
    ReorderLevel: 25,
    Status: "Validated",
    Category: {
      CategoryID: 2,
      CategoryName: "Condiments",
      Description: "Sweet and savory sauces, relishes, spreads, and seasonings",
    },
    FirstOrderedOn: new Date(2022, 2, 20),
    LastOrderedOn: new Date(2022, 4, 22),
  },
  {
    ProductID: "WP-0010019",
    ProductName: "WP-0010019",
    SupplierID: 3,
    CategoryID: 7,
    QuantityPerUnit: "12 - 1 lb pkgs.",
    UnitPrice: 30,
    UnitsInStock: 15,
    UnitsOnOrder: 0,
    ReorderLevel: 10,
    Status: "pending for Approval",
    Category: {
      CategoryID: 7,
      CategoryName: "Produce",
      Description: "Dried fruit and bean curd",
    },
    FirstOrderedOn: new Date(2022, 4, 20),
    LastOrderedOn: new Date(2022, 4, 22),
  },
  {
    ProductID: "WP-0010019",
    ProductName: "WP-0010019",
    SupplierID: 3,
    CategoryID: 2,
    QuantityPerUnit: "12 - 12 oz jars",
    UnitPrice: 40,
    UnitsInStock: 6,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Status: "Draft",
    Category: {
      CategoryID: 2,
      CategoryName: "Condiments",
      Description: "Sweet and savory sauces, relishes, spreads, and seasonings",
    },
    FirstOrderedOn: new Date(2022, 4, 20),
    LastOrderedOn: new Date(2022, 4, 22),
  },
  {
    ProductID: "WP-0010019",
    ProductName: "WP-0010019",
    SupplierID: 4,
    CategoryID: 6,
    QuantityPerUnit: "18 - 500 g pkgs.",
    UnitPrice: 97,
    UnitsInStock: 29,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Status: "pending for Approval",
    Category: {
      CategoryID: 6,
      CategoryName: "Meat/Poultry",
      Description: "Prepared meats",
    },
    FirstOrderedOn: new Date(2022, 2, 20),
    LastOrderedOn: new Date(2022, 5, 22),
  },
  {
    ProductID: "WP-0010019",
    ProductName: "WP-0010019",
    SupplierID: 4,
    CategoryID: 8,
    QuantityPerUnit: "12 - 200 ml jars",
    UnitPrice: 31,
    UnitsInStock: 31,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Status: "pending for Validation",
    Category: {
      CategoryID: 8,
      CategoryName: "Seafood",
      Description: "Seaweed and fish",
    },
    FirstOrderedOn: new Date(2022, 2, 20),
    LastOrderedOn: new Date(2022, 4, 22),
  },
];
